/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateGalleryDto } from '../../models/create-gallery-dto';
import { GalleryResponseDto } from '../../models/gallery-response-dto';

export interface GalleriesControllerCreate$Params {
      body: CreateGalleryDto
}

export function galleriesControllerCreate(http: HttpClient, rootUrl: string, params: GalleriesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<GalleryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, galleriesControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GalleryResponseDto>;
    })
  );
}

galleriesControllerCreate.PATH = '/api/galleries';
