/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GalleryResponseDto } from '../../models/gallery-response-dto';
import { UpdateGalleryDto } from '../../models/update-gallery-dto';

export interface GalleriesControllerUpdate$Params {
  id: string;
      body: UpdateGalleryDto
}

export function galleriesControllerUpdate(http: HttpClient, rootUrl: string, params: GalleriesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<GalleryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, galleriesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GalleryResponseDto>;
    })
  );
}

galleriesControllerUpdate.PATH = '/api/galleries/{id}';
