/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GalleryResponseDto } from '../../models/gallery-response-dto';

export interface GalleriesControllerList$Params {
  parentId?: string;
}

export function galleriesControllerList(http: HttpClient, rootUrl: string, params?: GalleriesControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GalleryResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, galleriesControllerList.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GalleryResponseDto>>;
    })
  );
}

galleriesControllerList.PATH = '/api/galleries';
