/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImageResponseDto } from '../../models/image-response-dto';

export interface ImagesControllerUpload$Params {
  galleryId: string;
      body: {
'file'?: Blob;
}
}

export function imagesControllerUpload(http: HttpClient, rootUrl: string, params: ImagesControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<ImageResponseDto>> {
  const rb = new RequestBuilder(rootUrl, imagesControllerUpload.PATH, 'post');
  if (params) {
    rb.path('galleryId', params.galleryId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImageResponseDto>;
    })
  );
}

imagesControllerUpload.PATH = '/api/galleries/{galleryId}/images';
