/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImageResponseDto } from '../../models/image-response-dto';

export interface ImagesControllerList$Params {
  galleryId: string;
}

export function imagesControllerList(http: HttpClient, rootUrl: string, params: ImagesControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ImageResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, imagesControllerList.PATH, 'get');
  if (params) {
    rb.path('galleryId', params.galleryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ImageResponseDto>>;
    })
  );
}

imagesControllerList.PATH = '/api/galleries/{galleryId}/images';
