/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GalleryResponseDto {
  childGalleryCount: number;
  createdAt: string;
  id: string;
  imageCount: number;
  name: string;
  parentId: {
} | null;
}
