/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageResponseDto {
  createdAt: string;
  displayUrl: string;
  galleryId: string;
  height: {
} | null;
  id: string;
  originalName: string;
  previewUrl: string;
  width: {
} | null;
}
