/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppControllerGetHello$Params as AppControllerGetHello$Params } from './fn/health/app-controller-get-hello';
export { appControllerGetHello as appControllerGetHello } from './fn/health/app-controller-get-hello';
export type { AuthControllerLogin$Params as AuthControllerLogin$Params } from './fn/auth/auth-controller-login';
export { authControllerLogin as authControllerLogin } from './fn/auth/auth-controller-login';
export type { GalleriesControllerList$Params as GalleriesControllerList$Params } from './fn/galleries/galleries-controller-list';
export { galleriesControllerList as galleriesControllerList } from './fn/galleries/galleries-controller-list';
export type { GalleriesControllerCreate$Params as GalleriesControllerCreate$Params } from './fn/galleries/galleries-controller-create';
export { galleriesControllerCreate as galleriesControllerCreate } from './fn/galleries/galleries-controller-create';
export type { GalleriesControllerGet$Params as GalleriesControllerGet$Params } from './fn/galleries/galleries-controller-get';
export { galleriesControllerGet as galleriesControllerGet } from './fn/galleries/galleries-controller-get';
export type { GalleriesControllerDelete$Params as GalleriesControllerDelete$Params } from './fn/galleries/galleries-controller-delete';
export { galleriesControllerDelete as galleriesControllerDelete } from './fn/galleries/galleries-controller-delete';
export type { GalleriesControllerUpdate$Params as GalleriesControllerUpdate$Params } from './fn/galleries/galleries-controller-update';
export { galleriesControllerUpdate as galleriesControllerUpdate } from './fn/galleries/galleries-controller-update';
export type { ImagesControllerList$Params as ImagesControllerList$Params } from './fn/images/images-controller-list';
export { imagesControllerList as imagesControllerList } from './fn/images/images-controller-list';
export type { ImagesControllerUpload$Params as ImagesControllerUpload$Params } from './fn/images/images-controller-upload';
export { imagesControllerUpload as imagesControllerUpload } from './fn/images/images-controller-upload';
export type { ImagesControllerDelete$Params as ImagesControllerDelete$Params } from './fn/images/images-controller-delete';
export { imagesControllerDelete as imagesControllerDelete } from './fn/images/images-controller-delete';
