/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthResponseDto } from './models/auth-response-dto';
export type { AuthUserDto } from './models/auth-user-dto';
export type { CreateGalleryDto } from './models/create-gallery-dto';
export type { GalleryResponseDto } from './models/gallery-response-dto';
export type { ImageResponseDto } from './models/image-response-dto';
export type { LoginDto } from './models/login-dto';
export type { UpdateGalleryDto } from './models/update-gallery-dto';
